# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/laszlo/laszlo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/laszlo/laszlo/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/runner/work/laszlo/laszlo/build && $(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/laszlo/laszlo/build/CMakeFiles /home/runner/work/laszlo/laszlo/build/src//CMakeFiles/progress.marks
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/laszlo/laszlo/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/runner/work/laszlo/laszlo/build && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
src/CMakeFiles/laszlo.dir/rule:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src/CMakeFiles/laszlo.dir/rule
.PHONY : src/CMakeFiles/laszlo.dir/rule

# Convenience name for target.
laszlo: src/CMakeFiles/laszlo.dir/rule
.PHONY : laszlo

# fast build rule for target.
laszlo/fast:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/build
.PHONY : laszlo/fast

expressions/struct_literal.o: expressions/struct_literal.cpp.o
.PHONY : expressions/struct_literal.o

# target to build an object file
expressions/struct_literal.cpp.o:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/expressions/struct_literal.cpp.o
.PHONY : expressions/struct_literal.cpp.o

expressions/struct_literal.i: expressions/struct_literal.cpp.i
.PHONY : expressions/struct_literal.i

# target to preprocess a source file
expressions/struct_literal.cpp.i:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/expressions/struct_literal.cpp.i
.PHONY : expressions/struct_literal.cpp.i

expressions/struct_literal.s: expressions/struct_literal.cpp.s
.PHONY : expressions/struct_literal.s

# target to generate assembly for a file
expressions/struct_literal.cpp.s:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/expressions/struct_literal.cpp.s
.PHONY : expressions/struct_literal.cpp.s

interpreter.o: interpreter.cpp.o
.PHONY : interpreter.o

# target to build an object file
interpreter.cpp.o:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/interpreter.cpp.o
.PHONY : interpreter.cpp.o

interpreter.i: interpreter.cpp.i
.PHONY : interpreter.i

# target to preprocess a source file
interpreter.cpp.i:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/interpreter.cpp.i
.PHONY : interpreter.cpp.i

interpreter.s: interpreter.cpp.s
.PHONY : interpreter.s

# target to generate assembly for a file
interpreter.cpp.s:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/interpreter.cpp.s
.PHONY : interpreter.cpp.s

lexer.o: lexer.cpp.o
.PHONY : lexer.o

# target to build an object file
lexer.cpp.o:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/lexer.cpp.o
.PHONY : lexer.cpp.o

lexer.i: lexer.cpp.i
.PHONY : lexer.i

# target to preprocess a source file
lexer.cpp.i:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/lexer.cpp.i
.PHONY : lexer.cpp.i

lexer.s: lexer.cpp.s
.PHONY : lexer.s

# target to generate assembly for a file
lexer.cpp.s:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/lexer.cpp.s
.PHONY : lexer.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/main.cpp.s
.PHONY : main.cpp.s

parser.o: parser.cpp.o
.PHONY : parser.o

# target to build an object file
parser.cpp.o:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/parser.cpp.o
.PHONY : parser.cpp.o

parser.i: parser.cpp.i
.PHONY : parser.i

# target to preprocess a source file
parser.cpp.i:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/parser.cpp.i
.PHONY : parser.cpp.i

parser.s: parser.cpp.s
.PHONY : parser.s

# target to generate assembly for a file
parser.cpp.s:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/parser.cpp.s
.PHONY : parser.cpp.s

statements/function_definition.o: statements/function_definition.cpp.o
.PHONY : statements/function_definition.o

# target to build an object file
statements/function_definition.cpp.o:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/statements/function_definition.cpp.o
.PHONY : statements/function_definition.cpp.o

statements/function_definition.i: statements/function_definition.cpp.i
.PHONY : statements/function_definition.i

# target to preprocess a source file
statements/function_definition.cpp.i:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/statements/function_definition.cpp.i
.PHONY : statements/function_definition.cpp.i

statements/function_definition.s: statements/function_definition.cpp.s
.PHONY : statements/function_definition.s

# target to generate assembly for a file
statements/function_definition.cpp.s:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/statements/function_definition.cpp.s
.PHONY : statements/function_definition.cpp.s

statements/struct_definition.o: statements/struct_definition.cpp.o
.PHONY : statements/struct_definition.o

# target to build an object file
statements/struct_definition.cpp.o:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/statements/struct_definition.cpp.o
.PHONY : statements/struct_definition.cpp.o

statements/struct_definition.i: statements/struct_definition.cpp.i
.PHONY : statements/struct_definition.i

# target to preprocess a source file
statements/struct_definition.cpp.i:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/statements/struct_definition.cpp.i
.PHONY : statements/struct_definition.cpp.i

statements/struct_definition.s: statements/struct_definition.cpp.s
.PHONY : statements/struct_definition.s

# target to generate assembly for a file
statements/struct_definition.cpp.s:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/statements/struct_definition.cpp.s
.PHONY : statements/struct_definition.cpp.s

token.o: token.cpp.o
.PHONY : token.o

# target to build an object file
token.cpp.o:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/token.cpp.o
.PHONY : token.cpp.o

token.i: token.cpp.i
.PHONY : token.i

# target to preprocess a source file
token.cpp.i:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/token.cpp.i
.PHONY : token.cpp.i

token.s: token.cpp.s
.PHONY : token.s

# target to generate assembly for a file
token.cpp.s:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/token.cpp.s
.PHONY : token.cpp.s

types.o: types.cpp.o
.PHONY : types.o

# target to build an object file
types.cpp.o:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/types.cpp.o
.PHONY : types.cpp.o

types.i: types.cpp.i
.PHONY : types.i

# target to preprocess a source file
types.cpp.i:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/types.cpp.i
.PHONY : types.cpp.i

types.s: types.cpp.s
.PHONY : types.s

# target to generate assembly for a file
types.cpp.s:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/types.cpp.s
.PHONY : types.cpp.s

values/array.o: values/array.cpp.o
.PHONY : values/array.o

# target to build an object file
values/array.cpp.o:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/array.cpp.o
.PHONY : values/array.cpp.o

values/array.i: values/array.cpp.i
.PHONY : values/array.i

# target to preprocess a source file
values/array.cpp.i:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/array.cpp.i
.PHONY : values/array.cpp.i

values/array.s: values/array.cpp.s
.PHONY : values/array.s

# target to generate assembly for a file
values/array.cpp.s:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/array.cpp.s
.PHONY : values/array.cpp.s

values/char.o: values/char.cpp.o
.PHONY : values/char.o

# target to build an object file
values/char.cpp.o:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/char.cpp.o
.PHONY : values/char.cpp.o

values/char.i: values/char.cpp.i
.PHONY : values/char.i

# target to preprocess a source file
values/char.cpp.i:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/char.cpp.i
.PHONY : values/char.cpp.i

values/char.s: values/char.cpp.s
.PHONY : values/char.s

# target to generate assembly for a file
values/char.cpp.s:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/char.cpp.s
.PHONY : values/char.cpp.s

values/function.o: values/function.cpp.o
.PHONY : values/function.o

# target to build an object file
values/function.cpp.o:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/function.cpp.o
.PHONY : values/function.cpp.o

values/function.i: values/function.cpp.i
.PHONY : values/function.i

# target to preprocess a source file
values/function.cpp.i:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/function.cpp.i
.PHONY : values/function.cpp.i

values/function.s: values/function.cpp.s
.PHONY : values/function.s

# target to generate assembly for a file
values/function.cpp.s:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/function.cpp.s
.PHONY : values/function.cpp.s

values/integer.o: values/integer.cpp.o
.PHONY : values/integer.o

# target to build an object file
values/integer.cpp.o:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/integer.cpp.o
.PHONY : values/integer.cpp.o

values/integer.i: values/integer.cpp.i
.PHONY : values/integer.i

# target to preprocess a source file
values/integer.cpp.i:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/integer.cpp.i
.PHONY : values/integer.cpp.i

values/integer.s: values/integer.cpp.s
.PHONY : values/integer.s

# target to generate assembly for a file
values/integer.cpp.s:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/integer.cpp.s
.PHONY : values/integer.cpp.s

values/string.o: values/string.cpp.o
.PHONY : values/string.o

# target to build an object file
values/string.cpp.o:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/string.cpp.o
.PHONY : values/string.cpp.o

values/string.i: values/string.cpp.i
.PHONY : values/string.i

# target to preprocess a source file
values/string.cpp.i:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/string.cpp.i
.PHONY : values/string.cpp.i

values/string.s: values/string.cpp.s
.PHONY : values/string.s

# target to generate assembly for a file
values/string.cpp.s:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/string.cpp.s
.PHONY : values/string.cpp.s

values/string_iterator.o: values/string_iterator.cpp.o
.PHONY : values/string_iterator.o

# target to build an object file
values/string_iterator.cpp.o:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/string_iterator.cpp.o
.PHONY : values/string_iterator.cpp.o

values/string_iterator.i: values/string_iterator.cpp.i
.PHONY : values/string_iterator.i

# target to preprocess a source file
values/string_iterator.cpp.i:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/string_iterator.cpp.i
.PHONY : values/string_iterator.cpp.i

values/string_iterator.s: values/string_iterator.cpp.s
.PHONY : values/string_iterator.s

# target to generate assembly for a file
values/string_iterator.cpp.s:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/string_iterator.cpp.s
.PHONY : values/string_iterator.cpp.s

values/value.o: values/value.cpp.o
.PHONY : values/value.o

# target to build an object file
values/value.cpp.o:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/value.cpp.o
.PHONY : values/value.cpp.o

values/value.i: values/value.cpp.i
.PHONY : values/value.i

# target to preprocess a source file
values/value.cpp.i:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/value.cpp.i
.PHONY : values/value.cpp.i

values/value.s: values/value.cpp.s
.PHONY : values/value.s

# target to generate assembly for a file
values/value.cpp.s:
	cd /home/runner/work/laszlo/laszlo/build && $(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszlo.dir/build.make src/CMakeFiles/laszlo.dir/values/value.cpp.s
.PHONY : values/value.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... laszlo"
	@echo "... expressions/struct_literal.o"
	@echo "... expressions/struct_literal.i"
	@echo "... expressions/struct_literal.s"
	@echo "... interpreter.o"
	@echo "... interpreter.i"
	@echo "... interpreter.s"
	@echo "... lexer.o"
	@echo "... lexer.i"
	@echo "... lexer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... statements/function_definition.o"
	@echo "... statements/function_definition.i"
	@echo "... statements/function_definition.s"
	@echo "... statements/struct_definition.o"
	@echo "... statements/struct_definition.i"
	@echo "... statements/struct_definition.s"
	@echo "... token.o"
	@echo "... token.i"
	@echo "... token.s"
	@echo "... types.o"
	@echo "... types.i"
	@echo "... types.s"
	@echo "... values/array.o"
	@echo "... values/array.i"
	@echo "... values/array.s"
	@echo "... values/char.o"
	@echo "... values/char.i"
	@echo "... values/char.s"
	@echo "... values/function.o"
	@echo "... values/function.i"
	@echo "... values/function.s"
	@echo "... values/integer.o"
	@echo "... values/integer.i"
	@echo "... values/integer.s"
	@echo "... values/string.o"
	@echo "... values/string.i"
	@echo "... values/string.s"
	@echo "... values/string_iterator.o"
	@echo "... values/string_iterator.i"
	@echo "... values/string_iterator.s"
	@echo "... values/value.o"
	@echo "... values/value.i"
	@echo "... values/value.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/runner/work/laszlo/laszlo/build && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

